version: '3.8'

services:
    db_app:
        image: mysql:8.0
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: "${DB_DATABASE:-app}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-secret}"
        ports:
            - "${DB_PORT}:3306"
        command: mysqld --port=${DB_PORT} --character-set-server=utf8 --collation-server=utf8_unicode_ci
        networks:
            - internal

    php_app:
        build:
            context: .
            dockerfile: docker/dev.php.Dockerfile
        volumes:
            - ./:/var/www/
            - ./docker/dev.supervisor.action.conf:/etc/supervisor/conf.d/action.conf
        depends_on:
            -  db_app
        ports:
            - "9000"
        networks:
            - internal
            
    nginx_app:
        build:
            context: .
            dockerfile: docker/dev.nginx.Dockerfile
        volumes:
            - .:/var/www/
        ports:
            - "${APP_PORT}:80"
        depends_on:
            - php_app
        networks:
            - internal

    adminer_app:
        image: michalhosna/adminer
        ports:
            - "${PN_PORT}:8080"
        environment:
            ADMINER_DB: "${DB_DATABASE:-app}"
            ADMINER_PASSWORD: "${DB_PASSWORD:-secret}"
            ADMINER_SERVER: "${DB_HOST:-mysql}"
            ADMINER_USERNAME: "${DB_USERNAME:-app}"
            ADMINER_AUTOLOGIN: 1
        networks:
            - internal

    redis_app:
        image: redis:6.0
        command: --port ${REDIS_PORT}
        ports:
        - "${REDIS_PORT}:${REDIS_PORT}"
        volumes:
        - ./storage/redis:/data
        networks:
        - internal

           
networks:
    internal:
        driver: bridge